#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" INT TERM EXIT
echo "$BASHPID" > /run/$(basename $0).pid

if [[ -f /backup/.base ]]; then
	mkdir -p /backup/"$(date +%d%m%y)"
	rsync -cazvvb --link-dest=/backup/"$(date +%d%m%y)" $1/ /backup/principal/
else
	mkdir -p /backup/principal
	rsync -cazv $1/ /backup/principal/
	touch /backup/.base
fi

rm -f /run/$(basename $0).pid
trap - INT TERM EXIT
exit 0
