#!/bin/bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ $USER != root ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/rsyncbackup.pid; exit" INT TERM EXIT
echo "$BASHPID" > /run/rsyncbackup.pid

if [[ -f /backup/.base ]]; then
	mkdir -p /backup/"$(date +%d%m%y)"
	rsync -cazvvb --link-dest=/backup/"$(date +%d%m%y)" $1/ /backup/principal/
else
	mkdir -p /backup/principal
	rsync -cazv $1/ /backup/principal/
	touch /backup/.base
fi

rm -f /run/rsyncbackup.pid
trap - INT TERM EXIT
exit 0
